---
title: "linear_regression"
output: html_document
date: "2024-09-01"
authors: "Mariam Miari"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libraries
```{r}
rm(list = ls())
library(rio)
library(here)
library(readxl)
library(tidyverse)
```

```{r}
results_version <- '240830'
```

## data upload
```{r}
data_nontrans <- read_excel("../data/processed/MGS2.0/data_nds_filt_nontrans_9993_updated250208.xlsx")


data_trans <- read_excel("../data/processed/MGS2.0/data_nds_filt_CLRtrans_9993_updated250208.xlsx")

```

## data prep
```{r}
#fix colnames data_trans 
matching_columns <- grepl("hMGS", colnames(data_trans))
# 
# replace everything before "hMGS" with an empty string
colnames(data_trans)[matching_columns] <- sub(".*hMGS\\.", "hMGS.", colnames(data_trans)[matching_columns])

#fix colnames data_nontrans 
matching_columns2 <- grepl("hMGS", colnames(data_nontrans))
# 
# replace everything before "hMGS" with an empty string
colnames(data_nontrans)[matching_columns2] <- sub(".*hMGS\\.", "hMGS.", colnames(data_nontrans)[matching_columns2])

##############################for data_trans
#factor physical_activity
data_trans <- data_trans %>%
  mutate(physical_activity_f = factor(physical_activity)) %>%
  relocate(physical_activity_f, .after = physical_activity)

#factor smoking
data_trans <- data_trans %>%
  mutate(smoking_f = factor(smoking)) %>%
  relocate(smoking_f, .after = smoking)

data_trans <- data_trans %>% 
  mutate(male = sex == 1) %>%
  relocate(male, .after = sex)



#########################same for data non_trans
#factor physical_activity
data_nontrans <- data_nontrans %>%
  mutate(physical_activity_f = factor(physical_activity)) %>%
  relocate(physical_activity_f, .after = physical_activity)

#factor smoking
data_nontrans <- data_nontrans %>%
  mutate(smoking_f = factor(smoking)) %>%
  relocate(smoking_f, .after = smoking)

data_nontrans <- data_nontrans %>% 
  mutate(male = sex == 1) %>%
  relocate(male, .after = sex)

```

```{r}
#I ensured that both dfs have same column indices and dimensions
all(colnames(data_nontrans) %in% colnames(data_trans))

#species only
mgs_trans <- grep("hMGS", names(data_trans), value = TRUE)
mgs_nontrans <-grep("hMGS", names(data_nontrans), value = TRUE)
```

## variables
```{r}
confounders_base <- c('age', 'country_birth', 'Cohort')

confounders_full <- c('age', 'country_birth', 'Cohort', 'physical_activity_f', 'smoking_f', 'metformin', 'diab_diag', 'Fiber')
```

```{r}
BMI <- "BMI"

# df to store results
results <- data.frame(
  analysis = character(),
  outcome = character(),
  cohort = character(),
  model_name = character(),
  mgs = character(),
  n_obs = numeric(),
  est = numeric(),
  se = numeric(),
  ci_low = numeric(),
  ci_high = numeric(),
  p = numeric(),
  stringsAsFactors = FALSE
)

# fit the model 
bmi_analysis <- function(formula, data, mgs_each, model_name, analysis, interaction_term = NULL) {
  model <- glm(formula, data = data, family = "gaussian")
  
  summary_model <- summary(model)
  coefs <- summary_model$coefficients
  conf_int <- tryCatch(confint(model), error = function(e) NULL)
  
  # if interaction term is included
  if (!is.null(interaction_term)) {
    mgs_name <- paste0(mgs_each, ":maleTRUE")
    est_value <- coefs[interaction_term, "Estimate"]
    p_value <- coefs[interaction_term, "Pr(>|t|)"]
    se_value <- coefs[interaction_term, "Std. Error"]
    ci_low_value <- if (!is.null(conf_int)) conf_int[interaction_term, 1] else NA
    ci_high_value <- if (!is.null(conf_int)) conf_int[interaction_term, 2] else NA
  } else {
    mgs_name <- mgs_each
    est_value <- coefs[BMI, "Estimate"]
    p_value <- coefs[BMI, "Pr(>|t|)"]
    se_value <- coefs[BMI, "Std. Error"]
    ci_low_value <- if (!is.null(conf_int)) conf_int[BMI, 1] else NA
    ci_high_value <- if (!is.null(conf_int)) conf_int[BMI, 2] else NA
  }
  
  result_rows <- data.frame(
    analysis = analysis,
    outcome = BMI,
    cohort = "all_cohorts",
    model_name = model_name,
    mgs = mgs_name,
    n_obs = model$df.null +1,
    est = est_value,
    se = se_value,
    ci_low = ci_low_value,
    ci_high = ci_high_value,
    p = p_value,
    stringsAsFactors = FALSE
  )
  
  return(result_rows)
}

# linear regression on non-zero values
for (mgs_each in mgs_trans) {
  
  # filtering for non-zero indices
  non_zero_indices <- data_nontrans[[mgs_each]] != 0
  subset_df <- data_trans[non_zero_indices, ]

  # base and full models for all individuals
  formula_base <- as.formula(paste(mgs_each, "~", BMI, "+ male +", paste(confounders_base, collapse = "+")))
  formula_full <- as.formula(paste(mgs_each, "~", BMI, "+ male +", paste(confounders_full, collapse = "+")))

  # results for all individuals
  results <- rbind(results, bmi_analysis(formula_base, subset_df, mgs_each, paste("base_M1", BMI, sep = "_"), "all"))
  results <- rbind(results, bmi_analysis(formula_full, subset_df, mgs_each, paste("full_M1", BMI, sep = "_"), "all"))

  # stratified models for males
  results <- rbind(results, bmi_analysis(as.formula(paste(mgs_each, "~", BMI, "+", paste(confounders_base, collapse = "+"))), subset_df %>% filter(male == TRUE), mgs_each, paste("base_stratM1", BMI, "males", sep = "_"), "sex_stratification"))
  results <- rbind(results, bmi_analysis(as.formula(paste(mgs_each, "~", BMI, "+", paste(confounders_full, collapse = "+"))), subset_df %>% filter(male == TRUE), mgs_each, paste("full_stratM1", BMI, "males", sep = "_"), "sex_stratification"))

  # stratified models for females
  results <- rbind(results, bmi_analysis(as.formula(paste(mgs_each, "~", BMI, "+", paste(confounders_base, collapse = "+"))), subset_df %>% filter(male == FALSE), mgs_each, paste("base_stratM1", BMI, "females", sep = "_"), "sex_stratification"))
  results <- rbind(results, bmi_analysis(as.formula(paste(mgs_each, "~", BMI, "+", paste(confounders_full, collapse = "+"))), subset_df %>% filter(male == FALSE), mgs_each, paste("full_stratM1", BMI, "females", sep = "_"), "sex_stratification"))

  # interaction model
  formula_interaction_base <- as.formula(paste(mgs_each, "~", BMI, "* male", "+", paste(confounders_base, collapse = "+")))
  formula_interaction_full <- as.formula(paste(mgs_each, "~", BMI, "* male", "+", paste(confounders_full, collapse = "+")))
  interaction_term <- paste0(BMI, ":maleTRUE")
  results <- rbind(results, bmi_analysis(formula_interaction_base, subset_df, mgs_each, paste("base_intM1", BMI, sep = "_"), "interaction", interaction_term = interaction_term))
  results <- rbind(results, bmi_analysis(formula_interaction_full, subset_df, mgs_each, paste("full_intM1", BMI, sep = "_"), "interaction", interaction_term = interaction_term))
}

head(results)

```
## FDR correction per analysis
```{r}
results <- results %>%
  group_by(analysis) %>%
  mutate(p_value_adj = p.adjust(p, method = "fdr")) %>%
  ungroup()
```

## save results
```{r}
file_name <- here::here("results",paste0("results_linear_", results_version, ".xlsx"))
export(results, file_name)
```
