---
title: "gmm_abundance_data_prep_for_reg"
output: html_document
description: here I prepared the GMM data variables from '/Volumes/research/metabogut/BMI_2021/Louise_intermediate/data_log_filt5_n12028_update220608_221104.RData' which is a datafile that contains 12028 samples of lungut and upgut (filtered data 5%) and all variables needed.
The GMM abundance data was prepared from KO counts data under the following paths:
  1. /Volumes/research/metabogut/BMI_2021/data/processed/CM_output/lungut/2020-12-21_lungut_additional_tables_2/lungut03.koCounts.tsv.gz
  and
  2. /Volumes/research/metabogut/BMI_2021/data/processed/CM_output/upgut/upugut03.koCounts.tsv.gz
  
GMM script for abundance data prep is located under this path:
  /Volumes/research/metabogut/BMI_2021/enrichment_analysis/new_analysis_2208/data_preparation/GMM_script.Rmd
  
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = '/Volumes/research/metabogut/BMI_2021')
```

```{r}
rm(list = ls())
library(tidyverse)
library(matrixStats)
```

### read GMM abundance data
```{r}
abund_gmm <- read.csv('enrichment_analysis/new_analysis_2208/results/output_files/abundance.csv')
```


#### match with samples from MGS data and take necessary variables
This MGS data was created by Louise and is already filtered (5%)
```{r}
load("Louise_intermediate/data_log_filt5_n12028_update220608_221104.RData")


lunup <- data_log %>%
    transmute(sample_ID = `Data sample code`, male = sex == 1,
              country_birth = country_birth,Cohort = Cohort, plate = plate, age = age,
              physical_activity = physical_activity,
              physical_activity_f = factor(physical_activity), height = height, 
              metformin = metformin, PPI = PPI, antibiotics = antibiotics, 
              Fiber = Fiber, shannon = shannon, 
              waist = waist, WHR = WH_rat, WHR = WH_rat, BMI = BMI, BMI_3 = BMI_3, BMI_4 = BMI_4) %>%
                as.data.frame()

lunup$sample_ID <- gsub("_b", "", lunup$sample_ID)
lunup$sample_ID <- gsub("b", "", lunup$sample_ID)
lunup$sample_ID <- gsub("c", "", lunup$sample_ID)
```


#### Sanity check
Do all pheno IDs match all KO IDs?
```{r}

length(lunup$sample_ID);
length(colnames(abund_gmm)[-1]);

lungut_ids <- lunup$sample_ID[grep('lungut', lunup$sample_ID)]

all(lungut_ids %in% colnames(abund_gmm)[-1]); #TRUE

upgut_ids <- lunup$sample_ID[grep('upugut', lunup$sample_ID)]
all(upgut_ids %in% colnames(abund_gmm)[-1]) #TRUE
```

Take the whole dataset to match GMM sample Ids with lunup sample Ids

```{r}
gmmIDs = colnames(abund_gmm[-1])
gmm <- abund_gmm[,c('Module', intersect(gmmIDs, lunup$sample_ID))]

all(colnames(gmm)[-1] %in% lunup$sample_ID) #TRUE

```

```{r}
gmm_names <- gmm$Module
gmm_transpose <- as.data.frame(t(gmm))
gmm_transpose <- gmm_transpose[-1,] 
gmm_transpose[] <- lapply(gmm_transpose, as.numeric)
colnames(gmm_transpose) <- gmm_names

data_gmm <- merge(lunup, gmm_transpose , by.x = 'sample_ID', by.y = 'row.names', all = TRUE)
#re-oder the sample_ID variable in data_ko as in lunup (which is same order as in data_log)
data_gmm <- data_gmm[order(match(data_gmm[,1],lunup[,1])),]
#reset rownames
rownames(data_gmm) <- NULL

```

```{r}
rm(lunup,gmm, gmm_transpose, abund_gmm, data_log, 
    gmmIDs, gmm_names,lungut_ids, upgut_ids)

save.image(file ="enrichment_analysis/new_analysis_2208/data_preparation/data_gmm.RData")
```




