---
title: "linear_CLR_all_5"
output: html_document
date: "2024-09-01"
author: "Mariam Miari"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libraries
```{r}
rm(list = ls())
library(rio)
library(here)
library(readxl)
library(tidyverse)
```

```{r}
results_version <- '240917'
```

## data upload
```{r}
load("../data/gmm/data_gmm_CLRtrans.RData")
```

## data prep
```{r}
#fix colnames data_trans 
matching_columns <- grepl("MF", colnames(data_gmm))
# 
# replace everything before "hgmm" with an empty string
colnames(data_gmm)[matching_columns] <- sub(".*MF", "MF", colnames(data_gmm)[matching_columns])
##############################for data_trans
#factor physical_activity
data_gmm <- data_gmm %>%
  mutate(physical_activity_f = factor(physical_activity)) %>%
  relocate(physical_activity_f, .after = physical_activity)

#factor smoking
data_gmm <- data_gmm %>%
  mutate(smoking_f = factor(smoking)) %>%
  relocate(smoking_f, .after = smoking)

data_gmm <- data_gmm %>% 
  mutate(male = sex == 1) %>%
  relocate(male, .after = sex)
```


## variables
```{r}
confounders_base <- c('age', 'country_birth', 'Cohort')

confounders_full <- c('age', 'country_birth', 'Cohort', 'physical_activity_f', 'smoking_f', 'metformin', 'diab_diag', 'Fiber')
```

```{r}
data <- data_gmm
gmm <-grep("MF", names(data), value = TRUE)

BMI <- "BMI"

# df to store results
results <- data.frame(
  analysis = character(),
  outcome = character(),
  cohort = character(),
  model_name = character(),
  gmm = character(),
  n_obs = numeric(),
  est = numeric(),
  se = numeric(),
  ci_low = numeric(),
  ci_high = numeric(),
  p = numeric(),
  stringsAsFactors = FALSE
)

# fit the model and store results
bmi_analysis <- function(formula, data, gmm_each, model_name, analysis, interaction_term = NULL) {
  model <- glm(formula, data = data, family = "gaussian")
  
  summary_model <- summary(model)
  coefs <- summary_model$coefficients
  conf_int <- tryCatch(confint(model), error = function(e) NULL)
  
 # if interaction term is included
  if (!is.null(interaction_term)) {
    gmm_name <- paste0(gmm_each, ":maleTRUE")
    est_value <- coefs[interaction_term, "Estimate"]
    p_value <- coefs[interaction_term, "Pr(>|t|)"]
    se_value <- coefs[interaction_term, "Std. Error"]
    ci_low_value <- if (!is.null(conf_int)) conf_int[interaction_term, 1] else NA
    ci_high_value <- if (!is.null(conf_int)) conf_int[interaction_term, 2] else NA
  } else {
    gmm_name <- gmm_each
    est_value <- coefs[BMI, "Estimate"]
    p_value <- coefs[BMI, "Pr(>|t|)"]
    se_value <- coefs[BMI, "Std. Error"]
    ci_low_value <- if (!is.null(conf_int)) conf_int[BMI, 1] else NA
    ci_high_value <- if (!is.null(conf_int)) conf_int[BMI, 2] else NA
  }
    
  
  result_rows <- data.frame(
    analysis = analysis,
    outcome = BMI,
    cohort = "all_cohorts",
    model_name = model_name,
    gmm = gmm_name,
    n_obs = model$df.null + 1,
    est = est_value,
    se = se_value,
    ci_low = ci_low_value,
    ci_high = ci_high_value,
    p = p_value,
    stringsAsFactors = FALSE
  )
  
  return(result_rows)
}

for (gmm_each in gmm) {
  
  # base and full models for all individuals 
  formula_base <- as.formula(paste(gmm_each, "~", BMI, "+ male +", paste(confounders_base, collapse = "+")))
  formula_full <- as.formula(paste(gmm_each, "~", BMI, "+ male +", paste(confounders_full, collapse = "+")))
  
  # results for all individuals
  results <- rbind(results, bmi_analysis(formula_base, data, gmm_each, paste("base_M1", BMI, sep = "_"), "all"))
  results <- rbind(results, bmi_analysis(formula_full, data, gmm_each, paste("full_M1", BMI, sep = "_"), "all"))
  
  # stratified models for males
  results <- rbind(results, bmi_analysis(as.formula(paste(gmm_each, "~", BMI, "+", paste(confounders_base, collapse = "+"))), data %>% filter(male == TRUE), gmm_each, paste("base_stratM1", BMI, "males", sep = "_"), "sex_stratification"))
  results <- rbind(results, bmi_analysis(as.formula(paste(gmm_each, "~", BMI, "+", paste(confounders_full, collapse = "+"))), data %>% filter(male == TRUE), gmm_each, paste("full_stratM1", BMI, "males", sep = "_"), "sex_stratification"))
  
  # stratified models for females
  results <- rbind(results, bmi_analysis(as.formula(paste(gmm_each, "~", BMI, "+", paste(confounders_base, collapse = "+"))), data %>% filter(male == FALSE), gmm_each, paste("base_stratM1", BMI, "females", sep = "_"), "sex_stratification"))
  results <- rbind(results, bmi_analysis(as.formula(paste(gmm_each, "~", BMI, "+", paste(confounders_full, collapse = "+"))), data %>% filter(male == FALSE), gmm_each, paste("full_stratM1", BMI, "females", sep = "_"), "sex_stratification"))
  
  # interaction model
  formula_interaction_base <- as.formula(paste(gmm_each, "~", BMI, "* male", "+", paste(confounders_base, collapse = "+")))
  formula_interaction_full <- as.formula(paste(gmm_each, "~", BMI, "* male", "+", paste(confounders_full, collapse = "+")))
  interaction_term <- paste0(BMI, ":maleTRUE")
  results <- rbind(results, bmi_analysis(formula_interaction_base, data, gmm_each, paste("base_intM1", BMI, sep = "_"), "interaction", interaction_term = interaction_term))
  results <- rbind(results, bmi_analysis(formula_interaction_full, data, gmm_each, paste("full_intM1", BMI, sep = "_"), "interaction", interaction_term = interaction_term))
}


head(results)

```
## FDR correction per analysis
```{r}
results <- results %>%
  group_by(analysis) %>%
  mutate(p_value_adj = p.adjust(p, method = "fdr")) %>%
  ungroup()
```

## save results
```{r}
file_name <- here::here("results",paste0("results_linear_clr_all", results_version, ".xlsx"))
export(results, file_name)
```
