---
title: "logistic_regression"
output: html_document
date: "2024-08-30"
author: Mariam Miari
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libraries
```{r}
rm(list = ls())
library(rio)
library(here)
library(readxl)
library(tidyverse)
```

```{r}
results_version <- '240917'
```

## data upload
```{r}
data_nontrans <- read_excel("../data/processed/MGS2.0/data_nds_filt_nontrans_9993_updated250208.xlsx")
```

## data prep
```{r}
#fix colnames data_nontrans 
matching_columns <- grepl("hMGS", colnames(data_nontrans))
# 
# replace everything before "hMGS" with an empty string
colnames(data_nontrans)[matching_columns] <- sub(".*hMGS\\.", "hMGS.", colnames(data_nontrans)[matching_columns])

data <- data_nontrans

#factor physical_activity
data <- data %>%
  mutate(physical_activity_f = factor(physical_activity)) %>%
  relocate(physical_activity_f, .after = physical_activity)

#factor smoking
data <- data %>%
  mutate(smoking_f = factor(smoking)) %>%
  relocate(smoking_f, .after = smoking)

data <- data %>% 
  mutate(male = sex == 1) %>%
  relocate(male, .after = sex)

data <- data %>%
  mutate(age_sq = age^2) %>%
  relocate(age_sq, .after = age)

mgs_st <- which(colnames(data) == "shannon_nds") +1
shannon_st <- which(colnames(data) == "shannon_nds")
mgs_df <- data[,c(mgs_st:ncol(data))]

## transform mgs to binary
mgs_df_bin <- as.data.frame(lapply(mgs_df, function(x) ifelse(x > 0, 1, 0)))


#put all variables back
data <- cbind(data[,c(1:shannon_st)], mgs_df_bin)
```

## variables: no base model, only one with all confounders
```{r}

confounders_full <- c("age","age_sq","PC1","PC2","PC3","PC4","PC5","Cohort")
```

all and sex stratified analysis
```{r}
# mgs variables names
mgs <-grep("hMGS", names(data), value = TRUE)
prs_bmi <- "prs_bmi_stdev"
prs_s_bmi <- "prs_s_bmi_stdev"

# dataframe to store results
results <- data.frame(
  analysis = character(),
  outcome = character(),
  cohort = character(),
  model_name = character(),
  mgs = character(),
  n_obs = numeric(),
  est = numeric(),
  se = numeric(),
  ci_low = numeric(),
  ci_high = numeric(),
  or = numeric(),       # OR column
  or_ci_low = numeric(), # OR CI lower bound column
  or_ci_high = numeric(), # OR CI upper bound column
  p = numeric(),
  stringsAsFactors = FALSE
)

# fit the model and store results
prs_bmi_analysis <- function(formula, data, mgs_each, model_name, analysis, exposure,interaction_term = NULL) {
  model <- glm(formula, data = data, family = "binomial")
  
  summary_model <- summary(model)
  coefs <- summary_model$coefficients
  conf_int <- tryCatch(confint(model), error = function(e) NULL)
  
 # if interaction term is included
  if (!is.null(interaction_term)) {
    mgs_name <- paste0(mgs_each, ":maleTRUE")
    est_value <- coefs[interaction_term, "Estimate"]
    p_value <- coefs[interaction_term, "Pr(>|z|)"]
    se_value <- coefs[interaction_term, "Std. Error"]
    ci_low_value <- if (!is.null(conf_int)) conf_int[interaction_term, 1] else NA
    ci_high_value <- if (!is.null(conf_int)) conf_int[interaction_term, 2] else NA
  } else {
    mgs_name <- mgs_each
    est_value <- coefs[exposure, "Estimate"]
    p_value <- coefs[exposure, "Pr(>|z|)"]
    se_value <- coefs[exposure, "Std. Error"]
    ci_low_value <- if (!is.null(conf_int)) conf_int[exposure, 1] else NA
    ci_high_value <- if (!is.null(conf_int)) conf_int[exposure, 2] else NA
  }
  
  # exponentiate estimates and confidence intervals
  or_value <- exp(est_value)
  or_ci_low_value <- exp(ci_low_value)
  or_ci_high_value <- exp(ci_high_value)
    
  
  result_rows <- data.frame(
    analysis = analysis,
    outcome = prs_bmi,
    cohort = "all_cohorts",
    model_name = model_name,
    mgs = mgs_name,
    n_obs = model$df.null +1,
    est = est_value,
    se = se_value,
    ci_low = ci_low_value,
    ci_high = ci_high_value,
    or = or_value,                 # OR value
    or_ci_low = or_ci_low_value,   # OR CI lower bound
    or_ci_high = or_ci_high_value, # OR CI upper bound
    p = p_value,
    stringsAsFactors = FALSE
  )
  
  return(result_rows)
}

for (mgs_each in mgs) {
  
  # model for all individuals 
  formula_full <- as.formula(paste(mgs_each, "~", prs_bmi, "+ male +", paste(confounders_full, collapse = "+")))
  
  # results for all individuals
  results <- rbind(results, prs_bmi_analysis(formula_full, data, mgs_each, paste("full_M1", prs_bmi, sep = "_"), "all", prs_bmi))
  
  # stratified models for males
  results <- rbind(results, prs_bmi_analysis(as.formula(paste(mgs_each, "~", prs_s_bmi, "+", paste(confounders_full, collapse = "+"))), data %>% filter(male == TRUE), mgs_each, paste("full_stratM1", prs_s_bmi, "males", sep = "_"), "sex_stratification", prs_s_bmi))
  
  # stratified models for females
  results <- rbind(results, prs_bmi_analysis(as.formula(paste(mgs_each, "~", prs_s_bmi, "+", paste(confounders_full, collapse = "+"))), data %>% filter(male == FALSE), mgs_each, paste("full_stratM1", prs_s_bmi, "females", sep = "_"), "sex_stratification", prs_s_bmi))
  
  # interaction model
  formula_interaction_full <- as.formula(paste(mgs_each, "~", prs_s_bmi, "* male", "+", paste(confounders_full, collapse = "+")))
  interaction_term <- paste0(prs_s_bmi, ":maleTRUE")
  results <- rbind(results, prs_bmi_analysis(formula_interaction_full, data, mgs_each, paste("full_intM1", prs_s_bmi, sep = "_"), "interaction", prs_s_bmi, interaction_term = interaction_term))
}


head(results)

```
## FDR correction per analysis
```{r}
results <- results %>%
  group_by(analysis) %>%
  mutate(p_value_adj = p.adjust(p, method = "fdr")) %>%
  ungroup()
```

## save results
```{r}
file_name <- here::here("results",paste0("results_logistic_", results_version, ".xlsx"))
export(results, file_name)
```

